name: PoseTracker
options:
  bundleIdPrefix: com.posetracker
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true

targets:
  PoseTracker:
    type: application
    platform: iOS
    sources:
      - PoseTracker
    info:
      path: PoseTracker/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCameraUsageDescription: "This app needs access to camera to track your exercise poses"
        CFBundleDisplayName: PoseTracker
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.posetracker.app
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: PoseTracker/Info.plist
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        IPHONEOS_DEPLOYMENT_TARGET: 16.0
        TARGETED_DEVICE_FAMILY: 1,2
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES